app_host: "{{ app.name }}.{{ app.domain }}"
langfuse_host: "langfuse.{{ app.domain }}"
langfuse_namespace: "langfuse"
langfuse_secret_name: "langfuse"
salt_key_name: "salt"
encryption_key_name: "encryption-key"
nextauth_secret_name: "nextauth-secret"
postgresql_password_name: "postgresql-password"
clickhouse_password_name: "clickhouse-password"
redis_password_name: "redis-password"