---
- name: Create manifests directory for temp configuration
  ansible.builtin.file:
    path: /tmp/rke2
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  run_once: true

- name: Copy nginx-ingress manifest to first master
  ansible.builtin.template:
    src: ingress-nginx.yml.j2
    dest: /tmp/rke2/ingress-nginx.yml
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  run_once: true
  when:
    - ingress.class == "ingress-nginx"

- name: Install ingress controller
  ansible.builtin.command: >
    {{ rke2_kubectl_binary | default('/var/lib/rancher/rke2/bin/kubectl') }} 
    --kubeconfig {{kubeconfig_path}} apply -f /tmp/rke2/ingress-nginx.yml
  run_once: true
  become: true
  when:
    - ingress.class == "ingress-nginx"

- name: Copy kic manifest to first master
  ansible.builtin.template:
    src: kic.yml.j2
    dest: /tmp/rke2/kic.yml
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  run_once: true
  when:
    - ingress.class == "kic"

- name: Install kic
  ansible.builtin.command: >
    {{ rke2_kubectl_binary | default('/var/lib/rancher/rke2/bin/kubectl') }} 
    --kubeconfig {{kubeconfig_path}} apply -f /tmp/rke2/kic.yml
  run_once: true
  become: true
  when:
    - ingress.class == "kic"

- name: Copy traefik manifest to first master
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /tmp/rke2/traefik.yml
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  run_once: true
  when:
    - ingress.class == "traefik"

- name: Install traefik
  ansible.builtin.command: >
    {{ rke2_kubectl_binary | default('/var/lib/rancher/rke2/bin/kubectl') }} 
    --kubeconfig {{kubeconfig_path}} apply -f /tmp/rke2/traefik.yml  
  run_once: true
  become: true
  when:
    - ingress.class == "traefik"

