---
- name: Create manifests directory for temp configuration
  ansible.builtin.file:
    path: /tmp/rke2
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  run_once: true

- name: Copy monitoring stack manifest
  ansible.builtin.template:
    src: monitoring.yml.j2
    dest: /tmp/rke2/monitoring.yml
    owner: "{{ ansible_user_id }}"
    mode: "0755"
  run_once: true

- name: Apply monitoring stack manifest
  ansible.builtin.command: >
    {{ rke2_kubectl_binary | default('/var/lib/rancher/rke2/bin/kubectl') }} 
    --kubeconfig {{ kubeconfig_path }}
    apply -f /tmp/rke2/monitoring.yml
  register: apply_result
  changed_when: false
  run_once: true
  until: apply_result.rc == 0
  retries: 5
  become: true

- name: Wait for Prometheus operator deployment
  ansible.builtin.command: >
    {{ rke2_kubectl_binary | default('/var/lib/rancher/rke2/bin/kubectl') }} 
    --kubeconfig {{ kubeconfig_path }}
    -n monitoring wait deployment/kube-prometheus-stack-operator 
    --for=condition=Available=True --timeout=300s
  register: operator_wait
  changed_when: false
  run_once: true
  become: true
  retries: 10
  delay: 30

- name: Wait for Grafana deployment
  ansible.builtin.command: >
    {{ rke2_kubectl_binary | default('/var/lib/rancher/rke2/bin/kubectl') }} 
    --kubeconfig {{ kubeconfig_path }}
    -n monitoring wait deployment/kube-prometheus-stack-grafana 
    --for=condition=Available=True --timeout=300s
  register: grafana_wait
  changed_when: false
  run_once: true
  become: true
  retries: 10
  delay: 30 