---
# Infrastructure setup
- name: Deploy RKE2 Infrastructure
  hosts: all
  gather_facts: true
  tags:
    - infra
    - never
  roles:
    - role: server
      when: inventory_hostname in groups['rke2_servers']
      tags: server
    
    - role: agent
      when: inventory_hostname in groups['rke2_agents']
      tags: agent
    
    - role: post_server
      when: inventory_hostname in groups['rke2_servers']
      tags: post_server

# Application deployment
- name: Deploy Applications
  hosts: localhost
  connection: local
  gather_facts: false
  tags:
    - apps
  vars:
    kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/config"
  roles:
    - role: apps
      tags: 
        - apps
