---
- name: Create manifests directory on first master
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Deploy Canal configuration
  become: true
  template:
    src: canal-config.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/canal-config.yaml
    mode: '0644'
  when:
   - inventory_hostname == groups['rke2_servers'][0]
   - cni.type == "canal"