---
# Create required directories
- name: Create RKE2 directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/rancher/rke2
    - /var/lib/rancher/rke2
    - /var/lib/rancher/rke2/server/manifests
  become: true

# Configure RKE2 server
- name: Configure RKE2 server
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0600'
  become: true

# Deploy kubevip if enabled
- name: Deploy kubevip 
  ansible.builtin.include_tasks: kubevip.yml
  when:
    - kubevip.enabled | bool
    - inventory_hostname == groups['rke2_servers'][0]

# Deploy metallb if enabled
- name: Deploy metallb
  ansible.builtin.include_tasks: metallb.yml
  when:
    - metallb.enabled | default(false) | bool
    - inventory_hostname == groups['rke2_servers'][0]
    - not kubevip.svc_lb.enabled | bool

# Handle CNI configuration
- name: Install CNI
  ansible.builtin.include_tasks: cni.yml
  when:
    - cni.type is defined
    - inventory_hostname == groups['rke2_servers'][0]


- name: Download RKE2 installer script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0700'
  register: download_installer
  become: true

- name: Install RKE2 server 
  shell: |
    INSTALL_RKE2_VERSION={{ rke2_config.version }} /tmp/rke2-install.sh
    systemctl enable rke2-server
    systemctl start rke2-server
  args:
    creates: /usr/local/bin/rke2
  become: true


# Wait for subsequent servers to join and ready
- name: Wait for all servers to be ready
  when: inventory_hostname == groups['rke2_servers'][0]
  shell: |
    READY_NODES=$(/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes --no-headers | grep -w "Ready" | wc -l)
    EXPECTED_NODES={{ groups['rke2_servers'] | length }}
    if [ "$READY_NODES" -eq "$EXPECTED_NODES" ]; then
      echo "All $EXPECTED_NODES servers are ready"
      exit 0
    else
      echo "Waiting for servers to be ready. Current: $READY_NODES, Expected: $EXPECTED_NODES"
      exit 1
    fi
  register: nodes_ready
  until: nodes_ready.rc == 0
  retries: 20
  delay: 20
  changed_when: false
  become: true

- name: Get contents of manifests folder
  ansible.builtin.find:
    paths: /var/lib/rancher/rke2/server/manifests
    file_type: file
  register: rke2_server_manifests
  when:
    - inventory_hostname == groups['rke2_servers'][0]
  become: true

- name: Get sub dirs of manifests folder
  ansible.builtin.find:
    paths: /var/lib/rancher/rke2/server/manifests
    file_type: directory
  register: rke2_server_manifests_directories
  when:
    - inventory_hostname == groups['rke2_servers'][0]
  become: true

- name: Remove manifests and folders that are only needed for bootstrapping cluster
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ rke2_server_manifests.files }}"
    - "{{ rke2_server_manifests_directories.files }}"
  loop_control:
    label: "{{ item.path }}"
  when:
    - inventory_hostname == groups['rke2_servers'][0]
  become: true