---
# Create temp directory locally
- name: Create temporary directory for manifests
  ansible.builtin.tempfile:
    state: directory
    suffix: langfuse
  register: temp_dir
  delegate_to: localhost
  tags:
    - langfuse

# Generate HelmChart manifest locally
- name: Generate HelmChart manifest
  ansible.builtin.template:
    src: langfuse.yml.j2
    dest: "{{ temp_dir.path }}/langfuse-helm.yaml"
    mode: '0644'
  delegate_to: localhost
  tags:
    - langfuse

# Apply HelmChart manifest using kubectl
- name: Apply langfuse HelmChart
  ansible.builtin.command: >
    kubectl --kubeconfig {{ kubeconfig_path }} 
    apply -f {{ temp_dir.path }}/langfuse-helm.yaml
  delegate_to: localhost
  register: apply_result
  changed_when: "'created' in apply_result.stderr or 'configured' in apply_result.stderr"
  tags:
    - langfuse

# Clean up temp directory
- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent
  delegate_to: localhost
  tags:
    - langfuse