rke2_kubectl_binary: /var/lib/rancher/rke2/bin/kubectl
kubeconfig_path: /etc/rancher/rke2/rke2.yaml
metallb_available_timeout: 240s
letsencrypt_env: "{{ cert_manager.letsencrypt.env | default('staging') }}"
letsencrypt_production_server: "{{ cert_manager.letsencrypt.production.server | default('https://acme-v02.api.letsencrypt.org/directory') }}"
letsencrypt_staging_server: "{{ cert_manager.letsencrypt.staging.server | default('https://acme-staging-v02.api.letsencrypt.org/directory') }}"
letsencrypt_server: "{{ letsencrypt_staging_server if letsencrypt_env == 'staging' else letsencrypt_production_server }}"