---
- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  become: true

- name: Restart Wicked
  ansible.builtin.service:
    name: wicked
    state: restarted
  become: true 